build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related prod APIs "
  contactDetails:
    name: "Samim - Product Owner"
    email: "srsamim043@gmail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384