build:
  version: "3.0"

cards:
  message: "Welcome to cards related local APIs "
  contactDetails:
    name: "Samim - Developer"
    email: "srsamim043@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932